#ctrl chift k

---
title: "Fukuoka 항공권"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(RSelenium)
library(XML)
library(rvest)
library(stringr)
library(knitr)
library(dplyr)
library(tidyr)
library(lubridate)
library(httr)
library(readxl)
library(writexl)
library(jsonlite)
library(kableExtra)
library(DT)


rD <- rsDriver(browser="firefox", port=4764L, chromever=NULL)
remDr <- rD$client

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
# 네이버 항공권 웹사이트 접속
remDr$navigate("https://flight.naver.com/flights/")

# 목적지 드롭다운 메뉴 클릭
remDr$findElement(using = "css selector", value = ".select_name__XucEi")->destination_dropdown
destination_dropdown$clickElement()

# "일본" 선택
japan <- remDr$findElement(using = "xpath", value = "//*[@id="__next"]/div/main/div[10]/div[2]/section/section/button[2]]")
japan$clickElement()

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

